apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ../kanban-board-frontend/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: asi309/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: asi309/boards
      context: boards
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: asi309/columns
      context: columns
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: asi309/tasks
      context: tasks
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: asi309/kanban-board-frontend
      context: ../kanban-board-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.ts'
