apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: kanban.com
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /api/users/.*
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: /api/boards/.*
            backend:
              service:
                name: boards-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: /api/columns/.*
            backend:
              service:
                name: columns-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: /api/tasks/.*
            backend:
              service:
                name: tasks-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: /.*
            backend:
              service:
                name: kanban-board-frontend-srv
                port:
                  number: 3000
